### ISSUE TITLE
resource.h missing

### ISSUE THREAD

**Issue by Pugduddly** [TETYYS/SAPI4#1]
What the title says. I can't compile sapi4.cpp.

**Comment by TETYYS** [comment]
uhh, I don't think it's even used anywhere, try just removing the include

**Comment by Pugduddly** [comment]
I did and it fails to compile with this message (btw I'm using Visual Studio 2010)
![sapi4fail](https://user-images.githubusercontent.com/16000407/38118727-6a0be802-3382-11e8-9005-5ffb4d11edac.png)

**Comment by TETYYS** [comment]
This is not related to `resource.h`, but it looks like the is missing some opening or closing brackets.
