### ISSUE TITLE
Installing spchapi.exe and tv_enua.exe on headless linux

### ISSUE THREAD

**Issue by m-weeks** [TETYYS/SAPI4#13]
When I run `wine spchapi.exe` and `wine tv_enua.exe` to install on a linux server, it doesn't appear to do anything other than spit out a couple warnings / errors.

```
root@ea145433ab2b:/SAPI4# wine spchapi.exe 
0048:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0024:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0024:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
```
```
root@ea145433ab2b:/SAPI4# wine tv_enua.exe 
0108:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
00f8:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
```

How have you managed to install these on a headless linux? I'm assuming the issue is that the installers need to be clicked through but I'm unsure how that would even be done on headless linux

I have tried wine 3.0, 5.10, and 6.0.1 and it seems to be the same case for all.

**Comment by TETYYS** [comment]
you need to either need to temporarily install a DM (easy, but long way) or forward X11 through SSH (harder, not sure if works

**Comment by Ceralor** [comment]
I know this is already closed, but I found a proper workaround. Both of these packages accept the `/Q` argument to silent install, but they do still require a display. For that, install `xvfb-run` via your package manager, and then `xvfb-run wine spchapi.exe /Q` and `xvfb-run wine tv_enua.exe /Q` to install them silently. You may want to use it just in case to run the server if it errors too.
