### ISSUE TITLE
Non American English Voices crash the SAPI4 Server when used

### ISSUE THREAD

**Issue by Seamusmario** [TETYYS/SAPI4#16]
OS: Windows 10 21H2
When i try to use the non-english voices such as L&H UK English and Korean, the SAPI4 Server just closes when attempting to generate.
Server: https://bonkeyword.tk/SAPI4/

**Comment by juanroman74454811** [comment]
> OS: Windows 10 21H2 When i try to use the non-english voices such as L&H UK English and Korean, the SAPI4 Server just closes when attempting to generate. Server: https://bonkeyword.tk/SAPI4/

too bad so sad, this isnt being colobarated anymore, use the original page, https://tetyys.com/SAPI4/

**Comment by TETYYS** [comment]
the web server shouldn't close even if voice generation crashes, so more details needed

**Comment by TETYYS** [comment]
i mean technical details... like a stack trace?

**Comment by juanroman74454811** [comment]
> whenever i use a voice that is another language other than American English, the server refuses to generate the speech with the voice and the sapi4.exe executable crashes without warning

Please, please use the original TETTYS page, https://tetyys.com/SAPI4/ For the faint of heart,

**Comment by juanroman74454811** [comment]
> i mean technical details... like a stack trace?

t h a t i s n o t a n o p t i o n ,

**Comment by Seamusmario** [comment]
> i mean technical details... like a stack trace?

whenever i manage to get the server back up, i will see if there is a stacktrace

**Comment by juanroman74454811** [comment]
> > i mean technical details... like a stack trace?
> 
> whenever i manage to get the server back up, i will see if there is a stacktrace

I wonder if the server will back up,

**Comment by juanroman74454811** [comment]
If voice generation closes, It will refuse to generate the output then will make the sapi4.exe executable crashing without a warning, I tried this on firefox and it gave me a warning,

**Comment by TETYYS** [comment]
If you have a similar issue please create another ticket. Otherwise, if you can't provide more details, please stop commenting.

**Comment by Seamusmario** [comment]
just put the server back up and tried the british english voices, after trying to generate speech, it results in a bad gateway error and no error was logged in the console
![image](https://user-images.githubusercontent.com/33694155/192305280-ba97c92a-d187-47f8-b56f-a9c4ec702575.png)

**Comment by Seamusmario** [comment]
![image](https://user-images.githubusercontent.com/33694155/192307888-7a748757-c2c3-4e32-b319-cffb25557409.png)
this is what i see after debugging with VS2022

**Comment by TETYYS** [comment]
The reason that it exits is because its done by design --- sometimes when running the application in WINE under linux it can corrupt itself for some reason so that all voice generations are invalid. As application is run as a service, it auto-restarts itself.

In your case your first generation fails, so I suggest running `sapi4out.exe` manually yourself to see what you get:
`sapi4out.exe "Adult Female #1 British English (L&H)" 170 180 "soi soi soi"`

**Comment by Seamusmario** [comment]
the WAV file with the voice was created but sapi4.exe just closed after it was generated

**Comment by TETYYS** [comment]
Did you see the resulting file printed out by `sapi4out.exe`?

**Comment by TETYYS** [comment]
I mean printed out in console, not only generated file, the reason that web server terminates is that it doesn't capture any output from `sapi4out.exe`. It should capture the resulting audio file name.

**Comment by Seamusmario** [comment]
this is what printed out when i debugged sapi4oute.exe
![image](https://user-images.githubusercontent.com/33694155/192310728-d62d7d00-4523-480c-b52f-719ae9329e86.png)

**Comment by TETYYS** [comment]
If the generation is successful and it prints out the resulting filename but webserver doesn't catch it, then either the way you're running `sapi4out.exe` is different from how web server is running it, or dlang runtime doesn't capture stdout of `sapi4out.exe` process for some reason, which I doubt it wouldn't.

**Comment by Seamusmario** [comment]
the webserver thinks that the generated file doesn't exist even though it was generated

**Comment by TETYYS** [comment]
In that case an exception would be thrown as per `enforce` in vibe.d https://github.com/vibe-d/vibe-core/blob/82a6e3b5a0839a230df22df41a7b89e1b9a3bf43/source/vibe/core/file.d#L47

**Comment by Seamusmario** [comment]
well unfortunately there was no exception reported, at least for me, so i have no clue what's causing the bug here

**Comment by TETYYS** [comment]
Unfortunately either there is wrong information or not enough information provided regarding this issue, so I cannot debug this from current position.

**Comment by Seamusmario** [comment]
you can try reproducing this issue by installing the L&H British English voices on the device and attempt to use the voice with the SAPI4 server
