### ISSUE TITLE
Issue 2: Robosoft Five changes to Microsoft Sam in a 1/200 chance,

### ISSUE THREAD

**Issue by juanroman74454811** [TETYYS/SAPI4#18]
This has happened to me various times, Its bassicly switched my voice to Microsoft sam,

**Comment by TETYYS** [comment]
It might be because `srand` is initialized with a clock that is accurate to a second, so it might clash with some other user generating voice at that exact second, I'll go ahead and replace that with sometime more granual

**Comment by TETYYS** [comment]
https://github.com/TETYYS/SAPI4/commit/877d49a86dc0fee23907996c2136d0f8f9acb57f

Let me know if you encounter the same issue in the future
