### ISSUE TITLE
Failed to spawn process sapi4limits.exe

### ISSUE THREAD

**Issue by Bionic-Matt** [TETYYS/SAPI4#24]
Attempting to compile local windows server and am stuck at step 4. 

Using Visual Studio 2022 Community with the vcvars32 path defined correctly in build.bat

```
std.process.ProcessException@std\process.d(1358): Failed to spawn process "sapi4limits.exe" (The system cannot find the file specified.)
----------------
0x00E94B3F
0x00E948F2
0x00E8018E
Program exited with code 1
```
Guide mentions sapi4limits.exe but all I see is the.cpp. - am I missing something?

**Comment by TETYYS** [comment]
`build.bat` should build sapi4limits.exe https://github.com/TETYYS/SAPI4/blob/master/build.bat#L4

**Comment by Bionic-Matt** [comment]
Thanks, cl.exe was missing from path

The site deploys if I move sapi4limits.exe etc into the _web folder but only the bonzi voice shows in the dropdown and no sound plays.

**Comment by TETYYS** [comment]
That would happen if you had no voices installed

**Comment by Bionic-Matt** [comment]
Getting there, thanks so far

Site deployed with voices, now just SAPI4 is undefined within the console 

![image](https://user-images.githubusercontent.com/18178894/202048713-6b32651b-702b-4f7f-96fe-33b639853796.png)
