### ISSUE TITLE
Builds

### ISSUE THREAD

**Issue by feamsr00** [TETYYS/SAPI4#26]
Hi!

Have you considered offering builds for this? At least for windows.

(I know you have a couple binaries, but I refer to the server in particular: sapi4.exe, sapi4.dll, sapi4limits.exe, and sapi4out.exe)

**Comment by TETYYS** [comment]
I have not, especially that the demo website is still up.

**Comment by Daisreich** [comment]
it's simply easier to build it yourself

**Comment by Daisreich** [comment]
or just use the demo

**Comment by TETYYS** [comment]
The application doesn't receive constant updates so I don't see much point in automated builds. Building it manually shouldn't be too hard either
