### ISSUE TITLE
504 Gateway Time-out Problems

### ISSUE THREAD

**Issue by KadenVanciel** [TETYYS/SAPI4#4]
Every time I try to get on the website, it takes a long time to load, only for the 504 Gateway Time-out page to show up every time. WTF is going on, and why is no one being the good Samaritan and helping me? SamJoe404 should know how I feel as long as he is a Christian.

**Comment by TETYYS** [comment]
Hello, the issues section is for implementation of web interface and its backend, not the demo website which runs code (that is a bit different compared to this repository).
