### ISSUE TITLE
SAPI4 on Windows 10 Very Unstable.

### ISSUE THREAD

**Issue by Seamusmario** [TETYYS/SAPI4#5]
It just crashes every 5 seconds.

**Comment by TETYYS** [comment]
Please provide more information, is the SAPI4 server crashing, or is it web server? Stacktrace? Memory dump?

**Comment by Seamusmario** [comment]
SAPI4 Server. It crashes after multiple usage.

**Comment by Seamusmario** [comment]
I use it for my chat client BonziWORLD Revived and it doesn't seem to handle it well

**Comment by TETYYS** [comment]
How does it crash, do you have a minidump or a stacktrace?

**Comment by Seamusmario** [comment]
There is no dump made by the web server. I actually meant the web server, as it crashes after multiple usage on SAPI4. It closes without warning.

**Comment by TETYYS** [comment]
can you attach a debugger to it?

**Comment by Seamusmario** [comment]
Debugger?

**Comment by Seamusmario** [comment]
Like how?

**Comment by TETYYS** [comment]
https://wiki.dlang.org/Debuggers

**Comment by Seamusmario** [comment]
I installed the Win32 debugger just now.

**Comment by TETYYS** [comment]
Please refrain from using a bug report as a chat room

**Comment by Seamusmario** [comment]
oops

**Comment by Seamusmario** [comment]
How do i attach the debugger when i just installed it?

**Comment by TETYYS** [comment]
please search for that on internet
