### ISSUE TITLE
Can't access the website.

### ISSUE THREAD

**Issue by yourizuring** [TETYYS/SAPI4#7]
I can't access the website for some reason.
Why is this? What should I do? Can you fix this?
![image](https://user-images.githubusercontent.com/47860706/87875093-0951f200-c9cf-11ea-9f2c-ade5b31216e9.png)

**Comment by TETYYS** [comment]
Hello, the issues section is for implementation of web interface and its backend, not the demo website which runs code (that is a bit different compared to this repository).

**Comment by onute-scriptors** [comment]
> Hello, the issues section is for implementation of web interface and its backend, not the demo website which runs code (that is a bit different compared to this repository).

yep it's same getting a error because your server went in a shutdown
