### ISSUE TITLE
504 Gateway Error - NEED HELP!

### ISSUE THREAD

**Issue by TheKitsKats** [TETYYS/SAPI4#8]
hello admin, i started having this error 3 days ago, and it still pops up. do you have a way to fix this error? and let me know when the site will be back up and running, thanks!

**Comment by TETYYS** [comment]
what site?

**Comment by TheKitsKats** [comment]
i was referring to this one: https://tetyys.com/SAPI4

**Comment by TheKitsKats** [comment]
the microsoft sam online generator is down and not showing up on google

**Comment by TheKitsKats** [comment]
> i was referring to this one: https://tetyys.com/SAPI4

and this is your microsoft sam generator it's down

**Comment by TheKitsKats** [comment]
![Screenshot 2021-02-28 at 11 06 27 AM](https://user-images.githubusercontent.com/79800577/109426828-8a3d8700-79bd-11eb-8608-bfe89712c902.png)
![Screenshot 2021-02-28 at 11 05 48 AM](https://user-images.githubusercontent.com/79800577/109426829-8a3d8700-79bd-11eb-9c48-1582e3714693.png)

**Comment by TETYYS** [comment]
You seem to be confused, this repo is not for a website

**Comment by TheKitsKats** [comment]
where do i go to report an issue for the microsoft sam generator??
